---
layout: post
title: "Measuring Learning"
author: "Duncan Clark"
date: "September 8 2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = TRUE)
library(ggplot2)
library(ggduncan)
```

TLDR: Can we use sports training ideas to optimise learning?

To present a probably very contrived idea I had about measuring learning I'll first talk about how training in cycling has evolved over the last couple of decades.

Modern cycling training involves the use of mainly a power meter to track levels of performance. This allows an athelete to see objectively, how much energy they are putting into the bicycle each second, the idea being that more energy makes you go faster, bigger power number are better. Its simple! Train yourself so you can put out more power for longer. 

It turns out that knowing objectively what you are putting out is enourmously useful. When riding, after a little practice, it allows you to pace yourself almost perfectly in races, as well as completing precise training session to achieve your goals; 300 watts for 20 minutes is the same whatever the conditions. This allows a rider to measure objectively their strengths and weaknesses and then address them with precise training sessions to improve performance.

Long term training stress can also be monitored over weeks and months. The basic idea being that higher training stress should leave you fitter and able to ride faster for longer. However an athelete can only take so much training before risking overtraining and subsequent lack of motivation and results drop in performance. Quantifying this obejctively allows an athelete to develop a training plan that is at the sweetspot for their goals, available times and current fitness.

This all sounds great, and generally works quite well. With some arguing that this kind of objective training is why younger professional cyclists are now suceeding at the top level (Think Evenepoel, Bernal and Pogacar). So the question that came to me is why haven't we tried to measure other things likes this?

In particular what other areas of our lives are we interested in out performances ? The obvious one that springs to mind is learning, whether still in education or not continuous learning is one of the keys to success. Is there a way to objectively measure the amount an individual has thought or learnt over a particular period of time? Is this something that may be available in the future if it is not now?

For the following thoughts I assume such a system does exist, i.e. with continuous monitoring, one is able to track how much they are currently learning or thinking, and keep track of it over a longer time period.

Keeping track of learning could then allow an individual to make sure they are challenging themselves enough to improve, while also avoiding that brain fried experience at the end of a long day when productivity takes a nose dive.

If we could do that, we could similar to endurance training, try to peak for certain events not races in this case but perhaps exams or a crucial period for a project you're working on. One could tailor days off and hard training or learning days in the right places.

If we take the analogy further, in cycling some riders are suited to certain events e.g. time trialists that can go at a hard steady pace for a long time, track endurance riders that have excellent power for 5 minutes, or even sprinters  - unbeatalbe over 5-30 seconds. Maybe individual brains are also like that? Maybe fighter pilots are the mind sprinters and that old philosophy professor has a brain stuck in an ultra endurance race. If this is true one could then work on their weakness and essentially improve their overall performance by working on their weaknesses.

Things start to look worrying when I consider if crucial parts in your life are dictated by a certain type of thinking. Exams at school are typically 1-3 hours, if you're not built for that length of effort you might be stuck in a sticky situation! Imagine asking an Olmypic sprinter to run a marathon to kindly prove that he was a good athelete. We might be living in a world of cognitive all rounders, able to hurdle the barriers put in place, but no able to achieve the pinacle, due to lack of specialisation.















