---
layout: page
title: "Xafinity Share Save App"
author: "Duncan Clark"
header-includes: \usepackage{amsmath}\usepackage{amsfonts} \usepackage{amssymb}\usepackage{mathrsfs}\usepackage{amsthm}\usepackage{graphicx} \usepackage{float}\usepackage{url}\usepackage{epstopdf}
---

TLDR : I made a Black-Scholes call option pricing app [here](https://duncan-clark.shinyapps.io/xafinity_share_save_app/)

I previously worked for the actuarial consultancy Xafinity Consulting (Now XPS pensions group). Towards the end of my time there, after commiting to starting my PhD in a few months time, the company floated on the London Stock Exchange. As shares were now publically trades a share incentive plan was put in place.

Having recently studied financial Mathematics and armed with knowledge of the Black-Scholes model for option pricing, it was clear to me that this was a call option on the stock of the company. Wow, this is simple, all I have to do is make a Black-Scholes app and then play with the parameters to understand under which conditions the scheme might be a good deal!

To be part of the scheme, one could save up to 250 pounds a month. After 3 years you would have the option to purchase the final value of the pot worth of stock, at a 90% discount to the price 3 years ago. The idea being that you are invested in the company and want the stock price to rise, so will work harder to achieve this.

Have a play with the app and determine whether you think its a good deal!

